language: node_js
sudo: false
node_js:
- '0.10'
- '0.12'
- stable
script:
- npm test
after_success:
- npm run coveralls
before_install:
- openssl aes-256-cbc -K $encrypted_cb4d3d070e32_key -iv $encrypted_cb4d3d070e32_iv
  -in auth.js.enc -out test/resources/auth.js -d
